### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by baggepinnen** [JuliaML/OpenAIGym.jl#5]
I encountered several isntall issues while following the README

```
julia> Pkg.clone("https://github.com/tbreloff/MetaPkg.jl")
julia> using MetaPkg
julia> MetaPkg.add("MetaRL")
ERROR: UndefVarError: add not defined
```

Manual install...
```
julia> using OpenAIGym
INFO: Precompiling module OpenAIGym.
ERROR: LoadError: ArgumentError: Module StochasticOptimization not found in current path.
Run `Pkg.add("StochasticOptimization")` to install the StochasticOptimization package.
```
```
julia> Pkg.add("StochasticOptimization")
ERROR: unknown package StochasticOptimization
```

**Comment by baggepinnen** [comment]
I seem to have solved (at least partially) the issue using the install instructions in the readme of `Learn.jl`, maybe this is the prefered way of installing?

**Comment by yukota** [comment]
MetaPkg.add is changed to meta_add by https://github.com/tbreloff/MetaPkg.jl/commit/a39d9b316666d6dbe7e4c307f43ea16fd534cf30

**Comment by baggepinnen** [comment]
For future reference, to install this package and all other needed packages, I found this procedure to work
```julia
Pkg.clone("https://github.com/tbreloff/MetaPkg.jl")
using MetaPkg
meta_add("MetaRL")
```

**Comment by tejank10** [comment]
`meta_add("MetaRL")` asks for private key and passphrase

**Comment by JobJob** [comment]
Pretty sure this should work, please advise if otherwise:
```
Pkg.clone("https://github.com/JuliaML/OpenAIGym.jl.git")
```

**Comment by baggepinnen** [comment]
You need to have uploaded your ssh key to github.com for that to work

**Comment by JobJob** [comment]
> You need to have uploaded your ssh key to github.com for that to work

@baggepinnen You mean `Pkg.clone` or meta_add?
