### ISSUE TITLE
ERROR: UndefVarError: episode! not defined

### ISSUE THREAD

**Issue by baggepinnen** [JuliaML/OpenAIGym.jl#6]
The `hello world` example in the readme does not seem to work, no `episode!` function defined.

**Comment by tejank10** [comment]
Any idea about resolving this issue?

**Comment by baggepinnen** [comment]
https://github.com/JuliaML/OpenAIGym.jl/issues/5#issuecomment-337506299
If you follow these steps you should get the correct version of all relevant packages

**Comment by tejank10** [comment]
Thanks for #5 . I removed and reinstalled `MetaPkg` using suggested method. Still, the error persists.

**Comment by tejank10** [comment]
I guess its definition is commented in `old_episodes.jl` in Reinforce.jl
